//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acciones
    {
        public int IdAccion { get; set; }
        public Nullable<int> IdPlanDeAccion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdRango { get; set; }
        public Nullable<int> IdEncuesta { get; set; }
        public Nullable<int> IdBaseDeDatos { get; set; }
        public Nullable<int> AnioAplicacion { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string ProgramaCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string ProgramaModificacion { get; set; }
        public Nullable<System.DateTime> FechaHoraEliminacion { get; set; }
        public string UsuarioEliminacion { get; set; }
        public string ProgramaEliminacion { get; set; }
        public Nullable<int> Tipo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual TipoEstatus TipoEstatus { get; set; }
        public virtual PlanDeAccion PlanDeAccion { get; set; }
        public virtual Rango Rango { get; set; }
        public virtual Encuesta Encuesta { get; set; }
        public virtual Encuesta Encuesta1 { get; set; }
        public virtual Encuesta Encuesta2 { get; set; }
        public virtual BasesDeDatos BasesDeDatos { get; set; }
    }
}
