//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acciones
    {
        public int IdAccion { get; set; }
        public Nullable<int> IdPlanDeAccion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdRango { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual TipoEstatus TipoEstatus { get; set; }
        public virtual PlanDeAccion PlanDeAccion { get; set; }
        public virtual Rango Rango { get; set; }
    }
}
