//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaIngreso
    {
        public int ID { get; set; }
        public string RFC { get; set; }
        public string Correo { get; set; }
        public string Empresa { get; set; }
        public string Area { get; set; }
        public string Departamento { get; set; }
        public string Puesto { get; set; }
        public string Contacto { get; set; }
        public Nullable<System.DateTime> FechaContacto { get; set; }
        public string Temperatura { get; set; }
        public string Tos { get; set; }
        public string Malestar { get; set; }
        public string MalestarGastrico { get; set; }
        public string DifRespirar { get; set; }
        public System.DateTime Fecha { get; set; }
        public string dTemperatura { get; set; }
        public string DolorGarganta { get; set; }
        public string EscurrimientoNasal { get; set; }
        public string DolorCuerpo { get; set; }
        public string Conjuntivitis { get; set; }
        public string Enfermedades { get; set; }
        public string AltGustOlfato { get; set; }
    }
}
