//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstatusEmail
    {
        public int IdEstatusEmail { get; set; }
        public string Mensaje { get; set; }
        public string Destinatario { get; set; }
        public Nullable<int> IdEstatusMail { get; set; }
        public Nullable<int> IdBaseDeDatos { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string ProgramaCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string ProgramaModificacion { get; set; }
        public Nullable<System.DateTime> FechaHoraEliminacion { get; set; }
        public string UsuarioEliminacion { get; set; }
        public string ProgramaEliminacion { get; set; }
        public string MsgEnvio { get; set; }
        public Nullable<int> IdEncuesta { get; set; }
        public Nullable<int> noIntentos { get; set; }
    
        public virtual BasesDeDatos BasesDeDatos { get; set; }
        public virtual EstatusMail EstatusMail { get; set; }
        public virtual Encuesta Encuesta { get; set; }
    }
}
