//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoClima
    {
        public int IdHistorico { get; set; }
        public string Enfoque { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> IdTipoEntidad { get; set; }
        public string Entidad { get; set; }
        public Nullable<int> EntidadId { get; set; }
        public string EntidadNombre { get; set; }
        public Nullable<decimal> Promedio66R { get; set; }
        public Nullable<decimal> Promedio86R { get; set; }
        public Nullable<int> Esperadas { get; set; }
        public Nullable<int> Contestadas { get; set; }
        public Nullable<int> HC { get; set; }
        public Nullable<decimal> NivelParticipacion { get; set; }
        public Nullable<decimal> CalificacionGlobal { get; set; }
        public Nullable<decimal> NivelConfianza { get; set; }
        public Nullable<decimal> NivelCompromiso { get; set; }
        public Nullable<decimal> NivelColaboracion { get; set; }
        public Nullable<decimal> Creedibilidad { get; set; }
        public Nullable<decimal> Imparcialidad { get; set; }
        public Nullable<decimal> Orgullo { get; set; }
        public Nullable<decimal> Respeto { get; set; }
        public Nullable<decimal> Companierismo { get; set; }
        public Nullable<decimal> Coaching { get; set; }
        public Nullable<decimal> HabilidadesGerenciales { get; set; }
        public Nullable<decimal> AlineacionEstrategica { get; set; }
        public Nullable<decimal> PracticasCulturales { get; set; }
        public Nullable<decimal> ManejoDelCambio { get; set; }
        public Nullable<decimal> ProcesosOrganizacionales { get; set; }
        public Nullable<decimal> Preg1 { get; set; }
        public Nullable<decimal> Preg2 { get; set; }
        public Nullable<decimal> Preg3 { get; set; }
        public Nullable<decimal> Preg4 { get; set; }
        public Nullable<decimal> Preg5 { get; set; }
        public Nullable<decimal> Preg6 { get; set; }
        public Nullable<decimal> Preg7 { get; set; }
        public Nullable<decimal> Preg8 { get; set; }
        public Nullable<decimal> Preg9 { get; set; }
        public Nullable<decimal> Preg10 { get; set; }
        public Nullable<decimal> Preg11 { get; set; }
        public Nullable<decimal> Preg12 { get; set; }
        public Nullable<decimal> Preg13 { get; set; }
        public Nullable<decimal> Preg14 { get; set; }
        public Nullable<decimal> Preg15 { get; set; }
        public Nullable<decimal> Preg16 { get; set; }
        public Nullable<decimal> Preg17 { get; set; }
        public Nullable<decimal> Preg18 { get; set; }
        public Nullable<decimal> Preg19 { get; set; }
        public Nullable<decimal> Preg20 { get; set; }
        public Nullable<decimal> Preg21 { get; set; }
        public Nullable<decimal> Preg22 { get; set; }
        public Nullable<decimal> Preg23 { get; set; }
        public Nullable<decimal> Preg24 { get; set; }
        public Nullable<decimal> Preg25 { get; set; }
        public Nullable<decimal> Preg26 { get; set; }
        public Nullable<decimal> Preg27 { get; set; }
        public Nullable<decimal> Preg28 { get; set; }
        public Nullable<decimal> Preg29 { get; set; }
        public Nullable<decimal> Preg30 { get; set; }
        public Nullable<decimal> Preg31 { get; set; }
        public Nullable<decimal> Preg32 { get; set; }
        public Nullable<decimal> Preg33 { get; set; }
        public Nullable<decimal> Preg34 { get; set; }
        public Nullable<decimal> Preg35 { get; set; }
        public Nullable<decimal> Preg36 { get; set; }
        public Nullable<decimal> Preg37 { get; set; }
        public Nullable<decimal> Preg38 { get; set; }
        public Nullable<decimal> Preg39 { get; set; }
        public Nullable<decimal> Preg40 { get; set; }
        public Nullable<decimal> Preg41 { get; set; }
        public Nullable<decimal> Preg42 { get; set; }
        public Nullable<decimal> Preg43 { get; set; }
        public Nullable<decimal> Preg44 { get; set; }
        public Nullable<decimal> Preg45 { get; set; }
        public Nullable<decimal> Preg46 { get; set; }
        public Nullable<decimal> Preg47 { get; set; }
        public Nullable<decimal> Preg48 { get; set; }
        public Nullable<decimal> Preg49 { get; set; }
        public Nullable<decimal> Preg50 { get; set; }
        public Nullable<decimal> Preg51 { get; set; }
        public Nullable<decimal> Preg52 { get; set; }
        public Nullable<decimal> Preg53 { get; set; }
        public Nullable<decimal> Preg54 { get; set; }
        public Nullable<decimal> Preg55 { get; set; }
        public Nullable<decimal> Preg56 { get; set; }
        public Nullable<decimal> Preg57 { get; set; }
        public Nullable<decimal> Preg58 { get; set; }
        public Nullable<decimal> Preg59 { get; set; }
        public Nullable<decimal> Preg60 { get; set; }
        public Nullable<decimal> Preg61 { get; set; }
        public Nullable<decimal> Preg62 { get; set; }
        public Nullable<decimal> Preg63 { get; set; }
        public Nullable<decimal> Preg64 { get; set; }
        public Nullable<decimal> Preg65 { get; set; }
        public Nullable<decimal> Preg66 { get; set; }
        public Nullable<decimal> Preg67 { get; set; }
        public Nullable<decimal> Preg68 { get; set; }
        public Nullable<decimal> Preg69 { get; set; }
        public Nullable<decimal> Preg70 { get; set; }
        public Nullable<decimal> Preg71 { get; set; }
        public Nullable<decimal> Preg72 { get; set; }
        public Nullable<decimal> Preg73 { get; set; }
        public Nullable<decimal> Preg74 { get; set; }
        public Nullable<decimal> Preg75 { get; set; }
        public Nullable<decimal> Preg76 { get; set; }
        public Nullable<decimal> Preg77 { get; set; }
        public Nullable<decimal> Preg78 { get; set; }
        public Nullable<decimal> Preg79 { get; set; }
        public Nullable<decimal> Preg80 { get; set; }
        public Nullable<decimal> Preg81 { get; set; }
        public Nullable<decimal> Preg82 { get; set; }
        public Nullable<decimal> Preg83 { get; set; }
        public Nullable<decimal> Preg84 { get; set; }
        public Nullable<decimal> Preg85 { get; set; }
        public Nullable<decimal> Preg86 { get; set; }
        public string Director { get; set; }
        public string GerenteGeneral { get; set; }
        public string GerenteDepartamental { get; set; }
        public string Subgerente { get; set; }
        public string COORDINADOR_SUPERVISOR_JEFE { get; set; }
        public string Administrativo { get; set; }
        public string Comercial { get; set; }
        public string TECNICO_OPERATIVO { get; set; }
        public string Ant_menos_de_6_meses { get; set; }
        public string Ant_6_meses_1_anio { get; set; }
        public string Ant_1_a_2_anios { get; set; }
        public string Ant_3_a_5_anios { get; set; }
        public string Ant_6_a_10_anios { get; set; }
        public string Ant_mas_de_10_anios { get; set; }
        public string Sexo_Masculino { get; set; }
        public string Sexo_Femenino { get; set; }
        public string Primaria { get; set; }
        public string Secundaria { get; set; }
        public string Media_Tecnica { get; set; }
        public string Media_Superior { get; set; }
        public string Universidad_Incompleta { get; set; }
        public string Universidad_Completa { get; set; }
        public string PostGrado { get; set; }
        public string Planta { get; set; }
        public string Sindicalizado { get; set; }
        public string Honorarios { get; set; }
        public string Comisionistas { get; set; }
        public string Temporal { get; set; }
        public string Edad_18_A_22_ANIOS { get; set; }
        public string Edad_23_A_31_ANIOS { get; set; }
        public string Edad_32_A_39_ANIOS { get; set; }
        public string Edad_40_A_55_ANIOS { get; set; }
        public string Edad_56_ANIOS_O_MAS { get; set; }
        public Nullable<decimal> Bienestar { get; set; }
        public Nullable<decimal> Bio { get; set; }
        public Nullable<decimal> Psico { get; set; }
        public Nullable<decimal> Social { get; set; }
    }
}
