//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantillas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantillas()
        {
            this.Encuesta = new HashSet<Encuesta>();
        }
    
        public int IdPlantilla { get; set; }
        public Nullable<int> IdDetallePlantilla { get; set; }
        public Nullable<int> IdHeaderPlantilla { get; set; }
        public Nullable<int> IdFooterPlantilla { get; set; }
        public Nullable<int> IdBodyPlantilla { get; set; }
        public Nullable<int> IdTipoPlantilla { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string ProgramaCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string ProgramaModificacion { get; set; }
        public Nullable<System.DateTime> FechaHoraEliminacion { get; set; }
        public string UsuarioEliminacion { get; set; }
        public string ProgramaEliminacion { get; set; }
    
        public virtual BodyPlantilla BodyPlantilla { get; set; }
        public virtual DetallePlantilla DetallePlantilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuesta> Encuesta { get; set; }
        public virtual FooterPlantilla FooterPlantilla { get; set; }
        public virtual HeaderPlantilla HeaderPlantilla { get; set; }
        public virtual TipoEstatus TipoEstatus { get; set; }
        public virtual TipoPlantilla TipoPlantilla { get; set; }
    }
}
