//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preguntas()
        {
            this.ConfiguraRespuesta = new HashSet<ConfiguraRespuesta>();
            this.EmpleadoRespuestas = new HashSet<EmpleadoRespuestas>();
            this.EncuestaPregunta = new HashSet<EncuestaPregunta>();
            this.Respuestas = new HashSet<Respuestas>();
            this.ValoracionPreguntaPorSubcategoria = new HashSet<ValoracionPreguntaPorSubcategoria>();
            this.UsuarioRespuestas = new HashSet<UsuarioRespuestas>();
        }
    
        public int IdPregunta { get; set; }
        public Nullable<int> idEncuesta { get; set; }
        public string Pregunta { get; set; }
        public Nullable<decimal> Valoracion { get; set; }
        public string TipoControl { get; set; }
        public Nullable<int> IdCompetencia { get; set; }
        public Nullable<int> IdDesencadenador { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string ProgramaCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string ProgramaModificacion { get; set; }
        public Nullable<System.DateTime> FechaHoraEliminacion { get; set; }
        public string UsuarioEliminacion { get; set; }
        public string ProgramaEliminacion { get; set; }
        public string Enfoque { get; set; }
        public Nullable<int> IdTipoControl { get; set; }
        public string RespuestaCondicion { get; set; }
        public string PreguntasCondicion { get; set; }
        public Nullable<bool> Obligatoria { get; set; }
        public Nullable<int> Seccion { get; set; }
        public string EncabezadoSeccion { get; set; }
        public Nullable<int> SubSeccion { get; set; }
        public Nullable<int> IdEnfoque { get; set; }
        public Nullable<int> IdPreguntaPadre { get; set; }
        public Nullable<int> IdOrden { get; set; }
    
        public virtual Competencia Competencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguraRespuesta> ConfiguraRespuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoRespuestas> EmpleadoRespuestas { get; set; }
        public virtual Encuesta Encuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaPregunta> EncuestaPregunta { get; set; }
        public virtual Enfoque Enfoque1 { get; set; }
        public virtual TipoControl TipoControl1 { get; set; }
        public virtual TipoEstatus TipoEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuestas> Respuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValoracionPreguntaPorSubcategoria> ValoracionPreguntaPorSubcategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRespuestas> UsuarioRespuestas { get; set; }
    }
}
