//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTCL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORTCL()
        {
            this.DATAREPORTCL = new HashSet<DATAREPORTCL>();
        }
    
        public int IDREPORTCL { get; set; }
        public string NOMBRE { get; set; }
        public string TABLEHTML { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string ProgramaCreacion { get; set; }
        public string UnidadNegocio { get; set; }
        public string Enfoque { get; set; }
        public Nullable<int> noColumnas { get; set; }
        public string TABLEHTMLFILL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATAREPORTCL> DATAREPORTCL { get; set; }
    }
}
