//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.PuntuacionCompetencia = new HashSet<PuntuacionCompetencia>();
            this.UsuarioRespuestas = new HashSet<UsuarioRespuestas>();
            this.UsuarioEstatusEncuesta = new HashSet<UsuarioEstatusEncuesta>();
        }
    
        public int IdUsuario { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdBaseDeDatos { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string ProgramaCreacion { get; set; }
        public Nullable<System.DateTime> FechaHoraModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string ProgramaModificacion { get; set; }
        public Nullable<System.DateTime> FechaHoraEliminacion { get; set; }
        public string UsuarioEliminacion { get; set; }
        public string ProgramaEliminacion { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Puesto { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaAntiguedad { get; set; }
        public string Sexo { get; set; }
        public string Email { get; set; }
        public string TipoFuncion { get; set; }
        public string CondicionTrabajo { get; set; }
        public string GradoAcademico { get; set; }
        public string UnidadNegocio { get; set; }
        public string DivisionMarca { get; set; }
        public string AreaAgencia { get; set; }
        public string Departamento { get; set; }
        public string Subdepartamento { get; set; }
        public string EmpresaContratante { get; set; }
        public Nullable<int> IdResponsableRH { get; set; }
        public string NombreResponsableRH { get; set; }
        public Nullable<int> IdJefe { get; set; }
        public string NombreJefe { get; set; }
        public string PuestoJefe { get; set; }
        public Nullable<int> IdResponsableEstructura { get; set; }
        public string NombreResponsableEstructura { get; set; }
        public string ClaveAcceso { get; set; }
        public string RangoAntiguedad { get; set; }
        public string RangoEdad { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<int> CampoNumerico_1 { get; set; }
        public string CampoDeTexto_1 { get; set; }
        public Nullable<int> CampoNumerico_2 { get; set; }
        public string CampoDeTexto_2 { get; set; }
        public Nullable<int> CampoNumerico_3 { get; set; }
        public string CampoDeTexto_3 { get; set; }
    
        public virtual BasesDeDatos BasesDeDatos { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Perfil Perfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntuacionCompetencia> PuntuacionCompetencia { get; set; }
        public virtual TipoEstatus TipoEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRespuestas> UsuarioRespuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioEstatusEncuesta> UsuarioEstatusEncuesta { get; set; }
    }
}
