//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string Nombre { get; set; }
        public string CompanyName { get; set; }
        public string Descripcion { get; set; }
        public string Expr1 { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<int> NumeroEmpleado { get; set; }
        public string Expr2 { get; set; }
        public string ApellidoPaterno { get; set; }
        public Nullable<int> IdEncuesta { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public string RespuestaEmpleado { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public int IdEmpleadoRespuestas { get; set; }
    }
}
