//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDemo1
    {
        public int IdUsuarioRespuestas { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> IdEncuesta { get; set; }
        public Nullable<int> IdPregunta { get; set; }
        public string RespuestaUsuario { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<int> IdRespuesta { get; set; }
        public Nullable<int> IdEstatus { get; set; }
        public Nullable<System.DateTime> A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public Nullable<System.DateTime> D { get; set; }
        public string E { get; set; }
        public string F { get; set; }
        public Nullable<System.DateTime> G { get; set; }
        public string H { get; set; }
        public string I { get; set; }
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string ApellidoMaterno { get; set; }
        public string ApellidoPaterno { get; set; }
        public string AreaAgencia { get; set; }
        public string CampoDeTexto_1 { get; set; }
        public string CampoDeTexto_2 { get; set; }
        public string CampoDeTexto_3 { get; set; }
        public Nullable<int> CampoNumerico_1 { get; set; }
        public Nullable<int> CampoNumerico_2 { get; set; }
        public Nullable<int> CampoNumerico_3 { get; set; }
    }
}
